version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: blablablaroot
      MYSQL_DATABASE: civi
      MYSQL_USER: dev
      MYSQL_PASSWORD: DbDevPw
